language: generic
sudo: required
services:
  - docker

install: true

env:
  global:
  - GROUP=fjudith COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=load-test;
  - secure: "LNes6tHw40T5lyJ55qsP7gTcb/24146FBxO9ZwcmZ1R03JxniGOgtl2wzqJVNkatprnAyUBGAXyQVSUPT6EaNklOqp4LwkHzTxIBqPS8tujcXUInD6ZCUd95teDcwODTWJob1llgLGzkNNgFshwTdczKIkRaZSoLxldL6Shy1RU+PX5OnoXWz115IsyqNQChGHI++9vT4lxN7RdVHRID1vub9qTsd5HgVc7dVZuJSWn3jXdd1Vi5RGGSVLvIvvR8MQEhpap/TuM5A1QGmJdBp/SjjvLjrUm1Y7Ux4UGvwH3emfFxL99O6G+BwH7T9c8hIi2ZuIR79Sw78FxifIldc3FYbWBnP/7AgXLIYPH5I7LdU8BkRQJqquDzv+B4yvSDUoxF5f7o6t/bnzNbfIunypBRD2MnUv8A80sbiyHvoQI8LgSlKg9bY6WRb7JDd0D/Scs0KVL8W+3WBOOMUAYi1jCHF4wyXo/fTiBn6myb1O0ic5NhPx3/jeN9pGYllX/hiz29rR80ZXwj+hgiB12h6lz+8kdDkC6pOr5wEPrrmY+Ng128fH1dafRmu3zPYJI10wX127z27dF+lRUGFfd7C0cnoMbPwpDxRoeCoGz4xpBTQERLKeNwI4zHRWmEVHQTTUZZKPkfz66SoN3m33UnEo0XyZUoPY7j57+AqpTmFxw="
  - secure: "wmdHgnxB0sHoohpJvuoTJ54O5t0VqHEoWH6D305uXoB/1fEn9xhB+k9z7pN/IRQl6ArB/P11pMOWQyP9XG7pSqNtApaM6vYVT9Bon0YWP6k4bhVT1povs96gozP94DV0OYeIJtDBmQPSpUpTfoGf/ynTEhX2MH/wLG8weg6+OZ59OKTsnOuR5RKD6u32oMKC1dQMLs96316IdEFvLx1VjW99BKOkc7pIQdiLpSfv4feQPCMkN9UDMq2GnuOgWPtCBEuze0QTBXgXYNrC6yDsbtybqPFt1gs5FtTWqZKd9HIVX/l82Q6EppyedZ7rHS5uTdyq7W7OLdeovEenKXJbA4wFhIUI5NcrfH3p7JrQ05it0Uje0gIzkMZ9TqPeIJypRS/Q7mVOhk6H6tiTy4SkneF5L1ZEX5e8Ca7PWcEm+NRFEaJmBEhgQaQx8TjaKnO+1LS1NC/SOubSiAJJK+n7ILZg9Ga4UpIIXA1DmqgzrHGgGsye3PlrYVuZn+FctRDJ6V6oKJz0Km4C0zLcTemNoX9kgTZJ/EBMTc1ZapJAIHVNDDzJeUNK0xGjcXVnDGwqlq35m9V7FH2UQD6aGTlpJPItXfnJpmIeVWQ93YFDiGS3BGEZYEa+6IoY+GzyOe5za/Wmu4ebX6mOzXyCDVFCEOroJBtlynuXHQOeHH4z8yc="
  
script:
  - set -e
  - curl -o docker-compose.yml -sSL https://raw.githubusercontent.com/microservices-demo/microservices-demo/master/deploy/docker-compose/docker-compose.yml
  - docker-compose -f docker-compose.yml up -d
  - docker build -t ${GROUP}/${REPO}:${COMMIT} .
  - docker run --rm --net loadtest_default -t ${GROUP}/${REPO}:${COMMIT} -d 180 -h http://edge-router -c 250 -r 60

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -u $DOCKER_USER -p $DOCKER_PASS;
  - ./push.sh
